apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
//apply plugin: 'kotlin-android-extensions'
//if (getGradle().getStartParameter().getTaskRequests().toString().contains("Hms")) {
//    // nothing
//} else {
//    // nothing for now
//}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: "com.bugsnag.android.gradle"

android {
    compileSdkVersion versions.compileSdkVersion

    defaultConfig {
        applicationId versions.appId
        minSdkVersion versions.minSdkVersion
        targetSdkVersion versions.targetSdkVersion
        versionCode versions.versionCode
        versionName versions.versionName
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }

    signingConfigs {
        debugKeystore {
            storeFile file("../debug_certificate/debug_cert.jks")
            storePassword "android"
            keyAlias "debug_certificate"
            keyPassword "android"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debugKeystore
        }
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles  getDefaultProguardFile('proguard-android-optimize.txt'),
                'proguard-rules.pro',
                'proguard/proguard-rules.pro',
                'proguard/otto.pro',
                'proguard/retrofit.pro',
                'proguard/okio.pro',
                'proguard/crashlytics.pro',
                'proguard/support_design.pro',
                'proguard/support_v7.pro',
                'proguard/picasso.pro',
                'proguard/android.pro'
        }
        android.applicationVariants.all { variant ->
            variant.outputs.all {
                outputFileName = outputFileName.replace("app-", "ApkInfo-" + defaultConfig.versionName + "-").replace(".apk", "-[" + defaultConfig.versionCode + "].apk")
            }
        }
    }

    bugsnag {
        uploadNdkMappings = false
        // uploadJvmMappings = false // nie wysyla mapping - testowe build
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    bundle {
        language {
            enableSplit = true
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = true
        }
    }

    flavorDimensions "market"

    productFlavors {
        gms {
            buildConfigField "String", "BUILD_FOR_MARKET", "\"google\""
        }
        hms {
            buildConfigField "String", "BUILD_FOR_MARKET", "\"huawei\""
        }
        apk {
            buildConfigField "String", "BUILD_FOR_MARKET", "\"apk\""
            versionCode android.defaultConfig.versionCode * 1000
        }
    }
    namespace versions.appId
    //compileOptions {
    //    sourceCompatibility = 1.8
    //}


}

dependencies {
    implementation project(':module_user_info')
    implementation project(':app_base')
}

if (getGradle().getStartParameter().getTaskRequests().toString().contains("Hms")) {
    apply plugin: 'com.huawei.agconnect'
}


//apply plugin: 'com.google.gms.google-services'