apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.fabric'

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "com.wt.apkinfo"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 103
        versionName "2.0.3"
        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        debugKeystore {
            storeFile file("../debug_certificate/debug_cert.jks")
            storePassword "android"
            keyAlias "debug_certificate"
            keyPassword "android"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debugKeystore
        }
        release {
            minifyEnabled false
            proguardFiles  getDefaultProguardFile('proguard-android-optimize.txt'),
                'proguard-rules.pro',
                'proguard/proguard-rules.pro',
                'proguard/otto.pro',
                'proguard/retrofit.pro',
                'proguard/okio.pro',
                'proguard/crashlytics.pro',
                'proguard/support_design.pro',
                'proguard/support_v7.pro',
                'proguard/picasso.pro',
                'proguard/android.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation libraries.androidx.core_ktx
    implementation libraries.androidx.appcompat
    implementation libraries.androidx.lifecycle_extensions
    implementation libraries.androidx.fragment
    implementation libraries.androidx.fragment_ktx
    implementation libraries.androidx.recyclerview
    implementation libraries.androidx.constraintlayout

    implementation libraries.android.installreferrer

    implementation libraries.google.material
    implementation libraries.google.firebase.analytics

    implementation libraries.squareup.picasso

    implementation libraries.material_dialogs
    implementation libraries.crashlytics
    implementation libraries.kotlin

    implementation project(':module_user_info')
}
