plugins {
	id 'com.android.library'
	id 'kotlin-parcelize'
}

android {
	namespace versions.appId + ".base"
	compileSdk versions.compileSdkVersion

	defaultConfig {
		minSdkVersion versions.minSdkVersion
		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		consumerProguardFiles "consumer-rules.pro"
	}

	buildFeatures {
		buildConfig = true
		viewBinding = true
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}

	kotlin {
		compilerOptions {
			jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
		}
	}

	flavorDimensions = ["market"]

	productFlavors {
		gms {
			buildConfigField "String", "BUILD_FOR_MARKET", "\"google\""
			buildConfigField "String", "APP_VERSION_NAME", "\"" + versions.versionName + "\""
		}
		//hms {
		//	buildConfigField "String", "BUILD_FOR_MARKET", "\"huawei\""
		//	buildConfigField "String", "APP_VERSION_NAME", "\"" + versions.versionName + "\""
		//}
		apk {
			buildConfigField "String", "BUILD_FOR_MARKET", "\"apk\""
			buildConfigField "String", "APP_VERSION_NAME", "\"" + versions.versionName + "\""
		}
	}
	lint {
		targetSdk 36
		disable 'MissingTranslation'
	}
	testOptions {
		targetSdk 36
	}
}

dependencies {
	implementation fileTree(dir: 'libs', include: ['*.jar'])

	implementation 'androidx.core:core-ktx:1.17.0'
	implementation "androidx.appcompat:appcompat:${versions.libs.androidx.appcompat}"
	implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.0'
	implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.0'
	implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.0'
	implementation 'androidx.fragment:fragment-ktx:1.8.9'
	implementation 'androidx.recyclerview:recyclerview:1.4.0'
	implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

	implementation 'com.android.installreferrer:installreferrer:2.2'

	implementation 'com.google.android.material:material:1.13.0'

	//noinspection GradleDependency
	implementation 'com.squareup.picasso:picasso:2.5.2' // its small and sufficient
	implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

	implementation("com.bugsnag:bugsnag-android:6.24.0") { // https://github.com/bugsnag/bugsnag-android
		exclude group: "com.bugsnag", module: "bugsnag-plugin-android-anr"
		exclude group: "com.bugsnag", module: "bugsnag-plugin-android-ndk"
	}

	implementation project(':module_user_info')
}
