plugins {
	id 'com.android.library'
	id 'org.jetbrains.kotlin.android'
	id 'org.jetbrains.kotlin.plugin.compose' version '2.2.20' // DODAJ TO
}

android {
	namespace versions.appId + ".base"
	compileSdk versions.compileSdkVersion

	defaultConfig {
		minSdkVersion versions.minSdkVersion
		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		consumerProguardFiles "consumer-rules.pro"

		//buildConfigField "String", "VERSION_NAME", "\"" + versions.versionName + "\""
	}

	buildFeatures {
		buildConfig = true
		viewBinding = true
		compose = true
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
	kotlinOptions {
		jvmTarget = '17'
	}

	flavorDimensions = ["market"]

	productFlavors {
		gms {
			buildConfigField "String", "BUILD_FOR_MARKET", "\"google\""
			buildConfigField "String", "APP_VERSION_NAME", "\"" + versions.versionName + "\""
		}
		hms {
			buildConfigField "String", "BUILD_FOR_MARKET", "\"huawei\""
			buildConfigField "String", "APP_VERSION_NAME", "\"" + versions.versionName + "\""
		}
		apk {
			buildConfigField "String", "BUILD_FOR_MARKET", "\"apk\""
			buildConfigField "String", "APP_VERSION_NAME", "\"" + versions.versionName + "\""
		}
	}
	lint {
		targetSdk 36
	}
	testOptions {
		targetSdk 36
	}
}

dependencies {
	implementation fileTree(dir: 'libs', include: ['*.jar'])

	implementation 'androidx.core:core-ktx:1.17.0'
	implementation "androidx.appcompat:appcompat:${versions.libs.androidx.appcompat}"
	implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.0'
	implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.0'
	implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.0'
	implementation 'androidx.fragment:fragment-ktx:1.8.9'
	implementation 'androidx.recyclerview:recyclerview:1.4.0'
	implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

	implementation 'com.android.installreferrer:installreferrer:2.2'

	implementation 'com.google.android.material:material:1.13.0'

	//noinspection GradleDependency
	implementation 'com.squareup.picasso:picasso:2.5.2' // its small and sufficient
	implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

	implementation("com.bugsnag:bugsnag-android:6.24.0") { // https://github.com/bugsnag/bugsnag-android
		exclude group: "com.bugsnag", module: "bugsnag-plugin-android-anr"
		exclude group: "com.bugsnag", module: "bugsnag-plugin-android-ndk"
	}

	implementation(platform("androidx.compose:compose-bom:2026.04.01"))
	implementation("androidx.compose.ui:ui")
	implementation("androidx.compose.material3:material3")
	implementation("androidx.compose.ui:ui-tooling-preview")
	implementation("androidx.activity:activity-compose:1.13.0")
	implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0")
	implementation("androidx.compose.runtime:runtime-livedata") // Do obsługi LiveData
	implementation("androidx.compose.foundation:foundation")
	implementation("androidx.compose.material:material-icons-core")

	implementation project(':module_user_info')
}